language: go
arch:
    - amd64
    - ppc64le
    - arm64
    - arm64-graviton2

go:
  - "1.18"
  - "1.19"

before_install:
  - go get github.com/xeipuuv/gojsonreference
  - go get github.com/xeipuuv/gojsonpointer
  - go get github.com/stretchr/testify/assert
